[package]
edition = "2024"
name = "dev-arg0"
version = { workspace = true }

[lib]
name = "dev_arg0"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = "1"
dev-apply-patch = { path = "../apply-patch" }
dev-core = { path = "../core" }
dev-linux-sandbox = { path = "../linux-sandbox" }
dotenvy = "0.15.7"
tempfile = "3"
tokio = { version = "1", features = ["rt-multi-thread"] }
