[package]
name = "dev-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "dev"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[lints]
workspace = true

[dependencies]
dev-core = { path = "../core", version = "0.7.0-dev.1" }
dev-protocol = { path = "../protocol", version = "0.7.0-dev.1" }
