@startuml hanzo
!pragma useIntermediatePackages false

class hanzo.action.agent.AgentEchoAction {
  content: str
  runnable: bool
  action: str
}
class hanzo.action.agent.AgentFinishAction {
  runnable: bool
  action: str
}
class hanzo.observation.AgentMessageObservation {
  role: str
  observation: str
}
class hanzo.action.agent.AgentSummarizeAction {
  summary: str
  action: str
}
class hanzo.action.agent.AgentThinkAction {
  thought: str
  runnable: bool
  action: str
}
class hanzo.action.base.ExecutableAction {
}
class hanzo.action.base.NotExecutableAction {
}
class hanzo.observation.Observation {
  content: str
}
class hanzo.action.base.Action {
}
class hanzo.action.base.NullAction {
  action: str
}
class hanzo.action.bash.CmdRunAction {
  command: str
  action: str
}
class hanzo.action.browse.BrowseURLAction {
  url: str
  action: str
}
class hanzo.observation.BrowserOutputObservation {
  url: str
  status_code: int
  error: bool
  observation: str
}
class hanzo.action.fileop.FileReadAction {
  path: str
  action: str
}
class hanzo.observation.FileReadObservation {
  path: str
  observation: str
}
class hanzo.action.fileop.FileWriteAction {
  path: str
  contents: str
  action: str
}
class hanzo.observation.FileWriteObservation {
  path: str
  observation: str
}
class hanzo.action.tasks.AddTaskAction {
  parent: str
  goal: str
  subtasks: list
  action: str
}
class hanzo.action.tasks.ModifyTaskAction {
  id: str
  state: str
  action: str
}
abstract class hanzo.agent.Agent {
  _registry: Dict[str, Type[Agent]] {static}
  llm: LLM
  _complete: None
}
class hanzo.llm.llm.LLM {
  model: None
  api_key: None
  base_url: None
  _debug_dir: None
  _debug_idx: None
  _debug_id: None
  _completion: None
}
class hanzo.controller.agent_controller.AgentController {
  agent: Agent
  max_iterations: int
  workdir: str
  command_manager: CommandManager
  state: State
  plan: Plan
  callbacks: List[Callable]
}
class hanzo.observation.AgentErrorObservation {
  observation: str
}
class hanzo.controller.command_manager.CommandManager {
  directory: None
  shell: None
}
class hanzo.observation.NullObservation {
  observation: str
}
class hanzo.plan.Plan {
  main_goal: str {static}
  task: Task {static}
  main_goal: str
  task: None
}
class hanzo.state.State {
  plan: Plan
  iteration: int
  history: List[Tuple[Action, Observation]]
  updated_info: List[Tuple[Action, Observation]]
}
class hanzo.observation.CmdOutputObservation {
  command: str
  exit_code: int
  observation: str
}
class hanzo.sandbox.sandbox.DockerInteractive {
  instance_id: None
  instance_id: None
  workspace_dir: None
  workspace_dir: None
  workspace_dir: None
  timeout: int
  base_container_image: None
  container_name: None
}
class hanzo.observation.UserMessageObservation {
  role: str
  observation: str
}
class hanzo.plan.Task {
  id: str {static}
  goal: str {static}
  parent: Task | None {static}
  subtasks: List[Task] {static}
  id: None
  id: None
  parent: None
  goal: str
  subtasks: None
}

class hanzo.server.session.Session {
  websocket: None
  controller: Optional[AgentController]
  agent: Optional[Agent]
  agent_task: None
}

hanzo.action.base.ExecutableAction <|-- hanzo.action.agent.AgentEchoAction
hanzo.action.base.NotExecutableAction <|-- hanzo.action.agent.AgentFinishAction
hanzo.observation.Observation <|-- hanzo.observation.AgentMessageObservation
hanzo.action.base.NotExecutableAction <|-- hanzo.action.agent.AgentSummarizeAction
hanzo.action.base.NotExecutableAction <|-- hanzo.action.agent.AgentThinkAction
hanzo.action.base.Action <|-- hanzo.action.base.ExecutableAction
hanzo.action.base.Action <|-- hanzo.action.base.NotExecutableAction
hanzo.action.base.NotExecutableAction <|-- hanzo.action.base.NullAction
hanzo.action.base.ExecutableAction <|-- hanzo.action.bash.CmdRunAction
hanzo.action.base.ExecutableAction <|-- hanzo.action.browse.BrowseURLAction
hanzo.observation.Observation <|-- hanzo.observation.BrowserOutputObservation
hanzo.action.base.ExecutableAction <|-- hanzo.action.fileop.FileReadAction
hanzo.observation.Observation <|-- hanzo.observation.FileReadObservation
hanzo.action.base.ExecutableAction <|-- hanzo.action.fileop.FileWriteAction
hanzo.observation.Observation <|-- hanzo.observation.FileWriteObservation
hanzo.action.base.NotExecutableAction <|-- hanzo.action.tasks.AddTaskAction
hanzo.action.base.NotExecutableAction <|-- hanzo.action.tasks.ModifyTaskAction
hanzo.agent.Agent *-- hanzo.agent.Agent
hanzo.agent.Agent *-- hanzo.llm.llm.LLM
hanzo.controller.agent_controller.AgentController *-- hanzo.agent.Agent
hanzo.observation.Observation <|-- hanzo.observation.AgentErrorObservation
hanzo.observation.Observation <|-- hanzo.observation.NullObservation
hanzo.plan.Plan *-- hanzo.plan.Task
hanzo.state.State *-- hanzo.plan.Plan
hanzo.state.State *-- hanzo.observation.CmdOutputObservation
hanzo.state.State *-- hanzo.action.base.Action
hanzo.state.State *-- hanzo.observation.Observation
hanzo.observation.Observation <|-- hanzo.observation.CmdOutputObservation
hanzo.observation.Observation <|-- hanzo.observation.UserMessageObservation
hanzo.plan.Task *-- hanzo.plan.Task
hanzo.server.session.Session *-- hanzo.controller.agent_controller.AgentController
hanzo.server.session.Session *-- hanzo.agent.Agent
hanzo.controller.agent_controller.AgentController -> hanzo.state.State
hanzo.controller.agent_controller.AgentController -> hanzo.plan.Plan
hanzo.controller.agent_controller.AgentController -> hanzo.controller.command_manager.CommandManager
hanzo.controller.command_manager.CommandManager -> hanzo.sandbox.sandbox.DockerInteractive

footer Based on f3fda42; Generated by //py2puml//
@enduml
