@startuml dev
!pragma useIntermediatePackages false

class dev.action.agent.AgentEchoAction {
  content: str
  runnable: bool
  action: str
}
class dev.action.agent.AgentFinishAction {
  runnable: bool
  action: str
}
class dev.observation.AgentMessageObservation {
  role: str
  observation: str
}
class dev.action.agent.AgentSummarizeAction {
  summary: str
  action: str
}
class dev.action.agent.AgentThinkAction {
  thought: str
  runnable: bool
  action: str
}
class dev.action.base.ExecutableAction {
}
class dev.action.base.NotExecutableAction {
}
class dev.observation.Observation {
  content: str
}
class dev.action.base.Action {
}
class dev.action.base.NullAction {
  action: str
}
class dev.action.bash.CmdRunAction {
  command: str
  action: str
}
class dev.action.browse.BrowseURLAction {
  url: str
  action: str
}
class dev.observation.BrowserOutputObservation {
  url: str
  status_code: int
  error: bool
  observation: str
}
class dev.action.fileop.FileReadAction {
  path: str
  action: str
}
class dev.observation.FileReadObservation {
  path: str
  observation: str
}
class dev.action.fileop.FileWriteAction {
  path: str
  contents: str
  action: str
}
class dev.observation.FileWriteObservation {
  path: str
  observation: str
}
class dev.action.tasks.AddTaskAction {
  parent: str
  goal: str
  subtasks: list
  action: str
}
class dev.action.tasks.ModifyTaskAction {
  id: str
  state: str
  action: str
}
abstract class dev.agent.Agent {
  _registry: Dict[str, Type[Agent]] {static}
  llm: LLM
  _complete: None
}
class dev.llm.llm.LLM {
  model: None
  api_key: None
  base_url: None
  _debug_dir: None
  _debug_idx: None
  _debug_id: None
  _completion: None
}
class dev.controller.agent_controller.AgentController {
  agent: Agent
  max_iterations: int
  workdir: str
  command_manager: CommandManager
  state: State
  plan: Plan
  callbacks: List[Callable]
}
class dev.observation.AgentErrorObservation {
  observation: str
}
class dev.controller.command_manager.CommandManager {
  directory: None
  shell: None
}
class dev.observation.NullObservation {
  observation: str
}
class dev.plan.Plan {
  main_goal: str {static}
  task: Task {static}
  main_goal: str
  task: None
}
class dev.state.State {
  plan: Plan
  iteration: int
  history: List[Tuple[Action, Observation]]
  updated_info: List[Tuple[Action, Observation]]
}
class dev.observation.CmdOutputObservation {
  command: str
  exit_code: int
  observation: str
}
class dev.sandbox.sandbox.DockerInteractive {
  instance_id: None
  instance_id: None
  workspace_dir: None
  workspace_dir: None
  workspace_dir: None
  timeout: int
  base_container_image: None
  container_name: None
}
class dev.observation.UserMessageObservation {
  role: str
  observation: str
}
class dev.plan.Task {
  id: str {static}
  goal: str {static}
  parent: Task | None {static}
  subtasks: List[Task] {static}
  id: None
  id: None
  parent: None
  goal: str
  subtasks: None
}

class dev.server.session.Session {
  websocket: None
  controller: Optional[AgentController]
  agent: Optional[Agent]
  agent_task: None
}

dev.action.base.ExecutableAction <|-- dev.action.agent.AgentEchoAction
dev.action.base.NotExecutableAction <|-- dev.action.agent.AgentFinishAction
dev.observation.Observation <|-- dev.observation.AgentMessageObservation
dev.action.base.NotExecutableAction <|-- dev.action.agent.AgentSummarizeAction
dev.action.base.NotExecutableAction <|-- dev.action.agent.AgentThinkAction
dev.action.base.Action <|-- dev.action.base.ExecutableAction
dev.action.base.Action <|-- dev.action.base.NotExecutableAction
dev.action.base.NotExecutableAction <|-- dev.action.base.NullAction
dev.action.base.ExecutableAction <|-- dev.action.bash.CmdRunAction
dev.action.base.ExecutableAction <|-- dev.action.browse.BrowseURLAction
dev.observation.Observation <|-- dev.observation.BrowserOutputObservation
dev.action.base.ExecutableAction <|-- dev.action.fileop.FileReadAction
dev.observation.Observation <|-- dev.observation.FileReadObservation
dev.action.base.ExecutableAction <|-- dev.action.fileop.FileWriteAction
dev.observation.Observation <|-- dev.observation.FileWriteObservation
dev.action.base.NotExecutableAction <|-- dev.action.tasks.AddTaskAction
dev.action.base.NotExecutableAction <|-- dev.action.tasks.ModifyTaskAction
dev.agent.Agent *-- dev.agent.Agent
dev.agent.Agent *-- dev.llm.llm.LLM
dev.controller.agent_controller.AgentController *-- dev.agent.Agent
dev.observation.Observation <|-- dev.observation.AgentErrorObservation
dev.observation.Observation <|-- dev.observation.NullObservation
dev.plan.Plan *-- dev.plan.Task
dev.state.State *-- dev.plan.Plan
dev.state.State *-- dev.observation.CmdOutputObservation
dev.state.State *-- dev.action.base.Action
dev.state.State *-- dev.observation.Observation
dev.observation.Observation <|-- dev.observation.CmdOutputObservation
dev.observation.Observation <|-- dev.observation.UserMessageObservation
dev.plan.Task *-- dev.plan.Task
dev.server.session.Session *-- dev.controller.agent_controller.AgentController
dev.server.session.Session *-- dev.agent.Agent
dev.controller.agent_controller.AgentController -> dev.state.State
dev.controller.agent_controller.AgentController -> dev.plan.Plan
dev.controller.agent_controller.AgentController -> dev.controller.command_manager.CommandManager
dev.controller.command_manager.CommandManager -> dev.sandbox.sandbox.DockerInteractive

footer Based on f3fda42; Generated by //py2puml//
@enduml
