// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputItem } from "./InputItem";
import type { ThreadId } from "./ThreadId";

/**
 * Steer a turn that is already running instead of replacing it.
 *
 * `sendUserMessage` submits `Op::UserInput`, which aborts the running task and
 * spawns a new one — the caller can interrupt, never redirect. This submits
 * `Op::QueueUserInput`, which folds the items into the turn already in flight.
 * With no turn running the two are equivalent.
 */
export type QueueUserMessageParams = { conversationId: ThreadId, items: Array<InputItem>, };
