//! Generated protobuf types
//!
//! This module includes the generated code from tonic-build.
//! The actual generated file is created by build.rs.

#[allow(clippy::all)]
#[allow(clippy::pedantic)]
#[allow(clippy::nursery)]
pub mod hanzo {
    pub mod node {
        pub mod v1 {
            // Include the generated code
            // This file is generated by build.rs from proto/hanzo.node.v1.proto
            include!(concat!(env!("OUT_DIR"), "/hanzo.node.v1.rs"));
        }
    }
}
